# This is a public repo that's built from the file 'Dockerfile.TexLive' and pushed to my dockerhub account 
# To use 'Dockerfile.TexLive' directly, change 'dockerFile' in 'devcontainer.json' to 'Dockerfile.TexLive'

FROM anuanandpremji/texlive
